# Dockerfile example.
#
# AUTHOR(s): Zaphod Beeblebrox <zaphodbe@cisco.com>
# CONTRIBUTOR(s): Arthur Dent <arthurde@cisco.com>
#                 Ford Prefect <fordpref@cisco.com>
#                 Slartibartfast <slartiba@cisco.com>


FROM {{image}}:{{tag}}


# Image Metadata
LABEL com.cisco.author="Zaphod Beeblebrox <zaphodbe@cisco.com>"


# Your build instructions here.
